package com.github.tartaricacid.mcshelper.util

object KeyboardTypes {
    data class Key(val name: String, val code: Int, val description: String) {
        override fun toString() = "$code · $name · $description"
    }

    val keys: List<Key> = listOf(
        Key("KEY_GOBACK", 4, "旧版本遗留，已弃用"),
        Key("KEY_MOUSE_LEFT", -99, "鼠标左键"),
        Key("KEY_MOUSE_RIGHT", -98, "鼠标右键"),
        Key("KEY_MOUSE_Middle", -97, "鼠标中键"),
        Key("KEY_BACKSPACE", 8, "Backspace键"),
        Key("KEY_TAB", 9, "Tab键"),
        Key("KEY_RETURN", 13, "回车键"),
        Key("KEY_PAUSE", 19, "PAUSE键"),
        Key("KEY_LSHIFT", 16, "SHIFT键"),
        Key("KEY_CONTROL", 17, "CONTROL键"),
        Key("KEY_MENU", 18, "ALT键"),
        Key("KEY_CAPS_LOCK", 20, "CAPS LOCK键(大小写键)"),
        Key("KEY_ESCAPE", 27, "Esc键"),
        Key("KEY_SPACE", 32, "空格键"),
        Key("KEY_PG_UP", 33, "Page Up键"),
        Key("KEY_PG_DOWN", 34, "Page Down键"),
        Key("KEY_END", 35, "End键"),
        Key("KEY_HOME", 36, "Home键"),
        Key("KEY_LEFT", 37, "方向左键(←)"),
        Key("KEY_UP", 38, "方向上键(↑)"),
        Key("KEY_RIGHT", 39, "方向右键(→)"),
        Key("KEY_DOWN", 40, "方向下键(↓)"),
        Key("KEY_INSERT", 45, "Insert键"),
        Key("KEY_DELETE", 46, "Delete键"),
        Key("KEY_0", 48, "数字0(大键盘不是小键盘，48~57同)"),
        Key("KEY_1", 49, "数字1"),
        Key("KEY_2", 50, "数字2"),
        Key("KEY_3", 51, "数字3"),
        Key("KEY_4", 52, "数字4"),
        Key("KEY_5", 53, "数字5"),
        Key("KEY_6", 54, "数字6"),
        Key("KEY_7", 55, "数字7"),
        Key("KEY_8", 56, "数字8"),
        Key("KEY_9", 57, "数字9"),
        Key("KEY_A", 65, "A键"),
        Key("KEY_B", 66, "B键"),
        Key("KEY_C", 67, "C键"),
        Key("KEY_D", 68, "D键"),
        Key("KEY_E", 69, "E键"),
        Key("KEY_F", 70, "F键"),
        Key("KEY_G", 71, "G键"),
        Key("KEY_H", 72, "H键"),
        Key("KEY_I", 73, "I键"),
        Key("KEY_J", 74, "J键"),
        Key("KEY_K", 75, "K键"),
        Key("KEY_L", 76, "L键"),
        Key("KEY_M", 77, "M键"),
        Key("KEY_N", 78, "N键"),
        Key("KEY_O", 79, "O键"),
        Key("KEY_P", 80, "P键"),
        Key("KEY_Q", 81, "Q键"),
        Key("KEY_R", 82, "R键"),
        Key("KEY_S", 83, "S键"),
        Key("KEY_T", 84, "T键"),
        Key("KEY_U", 85, "U键"),
        Key("KEY_V", 86, "V键"),
        Key("KEY_W", 87, "W键"),
        Key("KEY_X", 88, "X键"),
        Key("KEY_Y", 89, "Y键"),
        Key("KEY_Z", 90, "Z键"),
        Key("KEY_NUMPAD0", 96, "数字0(小键盘，96~111同)"),
        Key("KEY_NUMPAD1", 97, "数字1"),
        Key("KEY_NUMPAD2", 98, "数字2"),
        Key("KEY_NUMPAD3", 99, "数字3"),
        Key("KEY_NUMPAD4", 100, "数字4"),
        Key("KEY_NUMPAD5", 101, "数字5"),
        Key("KEY_NUMPAD6", 102, "数字6"),
        Key("KEY_NUMPAD7", 103, "数字7"),
        Key("KEY_NUMPAD8", 104, "数字8"),
        Key("KEY_NUMPAD9", 105, "数字9"),
        Key("KEY_MULTIPLY", 106, "乘号键(×)"),
        Key("KEY_ADD", 107, "加号键(+)"),
        Key("KEY_SUBTRACT", 109, "减号键(-)"),
        Key("KEY_DECIMAL", 110, "小数点(.)"),
        Key("KEY_DIVIDE", 111, "除法键(/)"),
        Key("KEY_F1", 112, "功能键F1"),
        Key("KEY_F2", 113, "功能键F2"),
        Key("KEY_F3", 114, "功能键F3"),
        Key("KEY_F4", 115, "功能键F4"),
        Key("KEY_F5", 116, "功能键F5"),
        Key("KEY_F6", 117, "功能键F6"),
        Key("KEY_F7", 118, "功能键F7"),
        Key("KEY_F8", 119, "功能键F8"),
        Key("KEY_F9", 120, "功能键F9"),
        Key("KEY_F10", 121, "功能键F10"),
        Key("KEY_F11", 122, "功能键F11"),
        Key("KEY_F12", 123, "功能键F12"),
        Key("KEY_F13", 124, "功能键F13"),
        Key("KEY_NUM_LOCK", 144, "Num Lock键"),
        Key("KEY_SCROLL", 145, "Scroll Lock键"),
        Key("KEY_SEMICOLON", 186, ": ; 键"),
        Key("KEY_EQUALS", 187, "= + 键"),
        Key("KEY_COMMA", 188, ", < 键"),
        Key("KEY_MINUS", 189, "- _ 键"),
        Key("KEY_PERIOD", 190, ". > 键"),
        Key("KEY_SLASH", 191, "/ ? 键"),
        Key("KEY_GRAVE", 192, "` ~ 键"),
        Key("KEY_LBRACKET", 219, "[ { 键"),
        Key("KEY_BACKSLASH", 220, "\\ | 键"),
        Key("KEY_RBRACKET", 221, "] } 键"),
        Key("KEY_APOSTRAPHE", 222, "' \" 键")
    )
}
